#!/system/bin/sh

if [ "a$2" != "a" ];then
  selinux=$2
fi

mount -o remount,rw /

case "${selinux}" in
  0)
    setenforce 0
    ;;
  1)
    setenforce 1
    ;;
esac;

mount -o remount,ro /

echo $selinux
